// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Useful for verifying MCP connectivity.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    return { content: [{ type: "text", text }] };
  }
});

// src/lib/mcp/tools/list-agents.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var AGENTS = [
  { name: "fabric-optimizer", role: "Topology auto-tuner", status: "executing" },
  { name: "thermal-guardian", role: "Cooling controller", status: "thinking" },
  { name: "cost-sentinel", role: "Spend optimizer", status: "idle" },
  { name: "incident-triage", role: "On-call AI SRE", status: "executing" },
  { name: "model-router", role: "LLM traffic shaper", status: "idle" },
  { name: "compliance-auditor", role: "Policy enforcement", status: "error" }
];
var list_agents_default = defineTool2({
  name: "list_agents",
  title: "List LightRail agents",
  description: "List the datacenter AI agents running in this LightOS deployment with their role and current status.",
  inputSchema: {
    status: z2.enum(["executing", "thinking", "idle", "error", "any"]).optional().describe("Filter by agent status. Defaults to 'any'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const filtered = !status || status === "any" ? AGENTS : AGENTS.filter((a) => a.status === status);
    return {
      content: [{ type: "text", text: JSON.stringify(filtered, null, 2) }],
      structuredContent: { agents: filtered }
    };
  }
});

// src/lib/mcp/tools/get-fabric-telemetry.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_fabric_telemetry_default = defineTool3({
  name: "get_fabric_telemetry",
  title: "Get photonic fabric telemetry",
  description: "Return a snapshot of photonic-fabric telemetry (utilization, latency, thermal) for the requested window in seconds.",
  inputSchema: {
    windowSeconds: z3.number().int().describe("Sampling window in seconds. Typical range 10-300.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ windowSeconds }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const w = Math.max(1, Math.min(600, windowSeconds));
    const snapshot = {
      windowSeconds: w,
      timestamp: (/* @__PURE__ */ new Date()).toISOString(),
      nodes: 240,
      utilizationPct: +(60 + Math.random() * 30).toFixed(1),
      p50LatencyUs: +(4 + Math.random() * 2).toFixed(2),
      p99LatencyUs: +(9 + Math.random() * 4).toFixed(2),
      avgTempC: +(62 + Math.random() * 8).toFixed(1),
      hotspots: Math.floor(Math.random() * 4),
      requestedBy: ctx.getUserEmail() ?? ctx.getUserId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(snapshot, null, 2) }],
      structuredContent: snapshot
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cawwhnuezkrsexjvetjj";
var mcp_default = defineMcp({
  name: "lightos-mcp",
  title: "LightOS / LightRail MCP",
  version: "0.2.0",
  instructions: "Tools for the LightOS photonic AI datacenter platform. All tools require an authenticated LightOS user (Supabase OAuth). Use `echo` to verify connectivity, `list_agents` to enumerate running datacenter agents, and `get_fabric_telemetry` to sample photonic fabric metrics.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [echo_default, list_agents_default, get_fabric_telemetry_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
